### ISSUE TITLE
Bug: very odd compiler error message

### ISSUE THREAD

**Issue by dukenguyenxyz** [elbywan/openapi-generator#15] opened 2021-04-16 02:07 UTC
#### System Information
```md
Crystal 1.0.0 (2021-03-22)

LLVM: 9.0.1
Default target: x86_64-apple-macosx
MacOS Catalina (10.15.7 19H2)
```

#### Note
- Please note I've tried my best to replicate and narrow down the bug as much as I can but this seems to be a more difficult task than I had initially conceived. Therefore, please excuse me for my lack of clarity. This is definitely a Crystal compiler error, but I only discovered in when using our current lib `openapi-generator` under very specific circumstances so I thought it's best to post it here.

#### Description
- When reopening a library class to extend `OpenAPI::Generator::Serializable`, but forgetting to extend `OpenAPI::Generator::Serializable` for the classes that are declared as types to the original library class' instance variable, raise a plain compiler error `Program received and didn't handle signal ILL (4)`.

#### Replication
This will be demonstrated with [PlaceOS/office365](https://github.com/PlaceOS/office365) [v1.13.2](https://github.com/PlaceOS/office365/releases/tag/v1.13.2) but any library would do, the `openapi-generator`'s version is [v1.0.2](https://github.com/elbywan/openapi-generator/releases/tag/v1.0.2).

`shard.yml`
```shard.yml
name: office365
version: 1.13.2

crystal: ">= 0.36.1, < 2.0.0"

dependencies:
  connect-proxy:
    github: spider-gazelle/connect-proxy
    version: ~> 1.0

  # OpenAPI Generator
  openapi-generator:
    github: elbywan/openapi-generator
    branch: master
  action-controller:
    github: spider-gazelle/action-controller
    version: ~> 4
  http-params-serializable:
    github: caspiano/http-params-serializable
    branch: chore/0.36.0

development_dependencies:
  webmock:
    github: manastech/webmock.cr
    branch: master
```

`example.cr`
```example.cr
require "json"

require "openapi-generator"
require "action-controller"
require "openapi-generator/providers/action-controller"
require "openapi-generator/helpers/action-controller"

require "./src/models/*"
require "./src/models/user"

module Office365
  class User
    extend ::OpenAPI::Generator::Serializable
  end

  # class Contact
  #   extend ::OpenAPI::Generator::Serializable
  # end

  # class EmailAddress
  #   extend ::OpenAPI::Generator::Serializable
  # end
end

OpenAPI::Generator.generate(
  OpenAPI::Generator::RoutesProvider::ActionController.new,
  options: {
    output: Path[Dir.current] / "schema.yaml",
  },
  base_document: {
    info:       {title: "Test", version: "123"},
    components: NamedTuple.new,
  }
)
```

This would raise `Program received and didn't handle signal ILL (4)`
```bash
crystal run ./example.cr
```

If we uncomment class `Contact` and `EmailAddress` extending `::OpenAPI::Generator::Serializable` then `crystal run ./example.cr` would produce `schema.yaml` normally.

#### What it should do
- Should raise something like the respective instance_var's class is not extending `::OpenAPI::Generator::Serializable`

**Comment by elbywan** [comment] 2021-04-16 07:57
@dukeraphaelng Thanks for reporting!

The issue is caused when a class member has an `Array`, `Tuple`, `NamedTuple` or `Hash` type having a generic type argument that is not openapi-serializable. For instance:

```crystal
module M
  class A
    extend ::OpenAPI::Generator::Serializable

    # The generator will fail to generate a proper schema for "b" because the class B is not serializable.
    property b : Array(B) = [] of B
  end

  class B
  end
end
```

I pushed a fix that will prevent the compiler from crashing.

**Closed as completed** 2021-04-28 10:31 UTC
Labels: bug
